apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-secret-es
  namespace: openshift-config
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: github-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: clientSecret
      remoteRef:
        key: cluster/moc-infra/github-client-secret
        property: clientSecret
