apiVersion: v1
kind: ConfigMap
metadata:
  name: idrac-exporter-config
data:
  idrac.yml: |
    address: 0.0.0.0
    port: 9348
    timeout: 20
    metrics:
      system: true
      sensors: true
      power: false
      events: true
      storage: false
      memory: false
      network: false
    events:
      severity: critical  # CONFIG_EVENTS_SEVERITY=warning
      maxage: 7d         # CONFIG_EVENTS_MAXAGE=7d
