apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  massopen.cloud/bundle: openshift-gitops-operator
resources:
- ../../base/namespaces/openshift-gitops-operator/
- ../../base/operators.coreos.com/operatorgroups/openshift-gitops-operator/
- ../../base/operators.coreos.com/subscriptions/openshift-gitops-operator/
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/argocd-allow-all/
- ../../base/rbac.authorization.k8s.io/clusterroles/argocd-allow-all/
