global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 3m
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'slack-alert-notifications'
  routes:
  - receiver: 'slack-alert-notifications'
    matchers:
      - job=~"idrac_.*||esi_.*|ipmi"

receivers:
- name: 'slack-alert-notifications'
  slack_configs:
  - api_url_file: /etc/alertmanager/secrets/webhook
    send_resolved: true
    title: >
      [{{ if eq .Status "firing" }}🔥 Firing{{ else }}✅ Resolved{{ end }}]
      {{ .CommonLabels.alertname }} on {{ .CommonLabels.instance }}
    text: >-
      *📢 Alert Group Summary*
      *Status:* {{ .Status }}
      *Instance:* {{ .CommonLabels.instance }}
      *Alert Count:* {{ len .Alerts }}

      *Group Labels:*
      {{ range $key, $value := .GroupLabels }}• *{{$key}}:* `{{$value}}`
      {{ end }}

      *Alerts List:*
      {{ range .Alerts }}
      • *{{ .Labels.severity | toUpper }}* — {{ .Annotations.summary }}
        _Description_: {{ .Annotations.description }}
        _Started_: {{ .StartsAt.Format "2006-01-02 15:04:05 MST" }}
      {{ end }}
      ---

inhibit_rules:
  - source_matchers:
      - scope = "component"
      - severity =~ "warning|critical"
    target_matchers:
      - scope = "system"
      - severity =~ "warning|critical"
    equal:
      - instance
