global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance']
  group_wait: 1s
  group_interval: 5m
  repeat_interval: 24h
  receiver: 'slack-alert-notifications'
  routes:
  - receiver: 'slack-alert-notifications'
    matchers:
      - job=~"idrac_exporter|idrac_snmp|ipmi"

receivers:
- name: 'slack-alert-notifications'
  slack_configs:
  - api_url_file: /etc/alertmanager/secrets/webhook
    send_resolved: true
    title: '[{{ if eq .Status "firing" }}Firing: 🔥{{ else }}Resolved: ✅{{ end }}] {{ .CommonLabels.alertname }} on {{ .CommonLabels.instance }}'
    text: >-
      {{ range .Alerts }}
        {{ .Annotations.description }}
      {{ end }}
