apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: idrac-credentials-es
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: idrac-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: username
      remoteRef:
        key: cluster/moc-infra/idrac-monitoring-secret
        property: username
    - secretKey: password
      remoteRef:
        key: cluster/moc-infra/idrac-monitoring-secret
        property: password
