apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ipmi-community-es
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: ipmi-snmp-community
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: community
      remoteRef:
        key: cluster/moc-infra/ipmi-community-string
        property: community
