apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  massopen.cloud/bundle: openshift-cert-manager-operator
resources:
- ../../base/namespaces/cert-manager-operator/
- ../../base/operators.coreos.com/operatorgroups/openshift-cert-manager-operator/
- ../../base/operators.coreos.com/subscriptions/openshift-cert-manager-operator/
