apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moc-monitoring

resources:
- ../../base
- externalsecrets

patches:
  - path: deployments/idrac-exporter_patch.yaml
  - path: deployments/ipmi-exporter_patch.yaml
  - path: deployments/snmp-exporter_patch.yaml
  - path: deployments/blackbox-exporter_patch.yaml
