apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 1m

    scrape_configs:
      - job_name: "idrac"
        static_configs:
          - targets: ['10.2.14.121']
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: idrac-exporter.moc-monitoring.svc:9348

      - job_name: "idrac_web"
        static_configs:
          - targets: ['10.2.14.121']
        metrics_path: /probe
        params:
          module:
          - http_302
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter.moc-monitoring.svc:9115

      - job_name: "idrac_ping"
        static_configs:
          - targets: ['10.2.14.121']
        metrics_path: /probe
        params:
          module:
          - ping
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter.moc-monitoring.svc:9115

      - job_name: "ipmi"
        params:
          module: ['default']
        metrics_path: /ipmi
        static_configs:
          - targets: ['10.2.14.121']
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: ipmi-exporter.moc-monitoring.svc:9290
