apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moc-monitoring

resources:
- deployment.yaml
- service.yaml
- pvc.yaml
- route.yaml

configMapGenerator:
- name: prometheus-rules
  files:
  - rules.yaml=config/prometheus-rules.yaml
  options:
    disableNameSuffixHash: true
- name: prometheus-config
  files:
  - prometheus.yml=config/prometheus-config.yaml
  options:
    disableNameSuffixHash: true
- name: cmc-targets
  files:
  - files/cmc_targets.yaml
  options:
    disableNameSuffixHash: true
- name: idrac-targets
  files:
  - files/idrac_targets.yaml
  options:
    disableNameSuffixHash: true
- name: lenovo-targets
  files:
  - files/lenovo_targets.yaml
  options:
    disableNameSuffixHash: true
