apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moc-monitoring

resources:
- deployment.yaml
- configmaps
- service.yaml
- pvc.yaml
- route.yaml

configMapGenerator:
- name: prometheus-rules
  files:
  - rules.yaml=config/prometheus-rules.yaml
  options:
    disableNameSuffixHash: true
- name: prometheus-config
  files:
  - prometheus.yml=config/prometheus-config.yaml
  options:
    disableNameSuffixHash: true
