apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ipmi-vlans
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
    - name: vlan911
      type: vlan
      state: up
      vlan:
        base-iface: ens3f0np0
        id: 911
    - name: vlan912
      type: vlan
      state: up
      vlan:
        base-iface: ens3f0np0
        id: 912
    - name: vlan913
      type: vlan
      state: up
      vlan:
        base-iface: ens3f0np0
        id: 913
