apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  massopen.cloud/bundle: metallb
resources:
- ../../base/core/namespaces/metallb-system/
- ../../base/operators.coreos.com/operatorgroups/metallb-system/
- ../../base/operators.coreos.com/subscriptions/metallb-system/
