apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  massopen.cloud/bundle: external-secrets
resources:
- ../../base/core/namespaces/external-secrets-operator
- ../../base/operators.coreos.com/subscriptions/external-secrets-operator
- ../../base/operators.coreos.com/operatorgroups/external-secrets
- ../../base/operator.external-secrets.io/operatorconfig/cluster
