apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moc-monitoring

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: blackbox-exporter-config
    options:
      disableNameSuffixHash: true
    files:
    - files/blackbox.yml
