apiVersion: v1
kind: ConfigMap
metadata:
  name: ipmi-exporter-config-template
data:
  config_template.yml: |
    modules:
      default:
        user: "{{ .Env.IPMI_USER }}"
        pass: "{{ .Env.IPMI_PASS }}"
        driver: "lanplus"
        privilege: "user"
        timeout: 10000
