apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moc-monitoring

resources:
- ../../base
- ../moc-infra/externalsecrets

patches:
- path: prometheus-alertmanager-patch.yaml
  target:
    kind: Deployment
    name: prometheus
- path: idrac-exporter-patch.yaml
  target:
    kind: Deployment
    name: idrac-exporter