apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moc-monitoring

resources:
- ../../base
- ../moc-infra/externalsecrets

patches:
- path: idrac-exporter-patch.yaml
  target:
    kind: Deployment
    name: idrac-exporter
- path: grafana-alerting-patch.yaml
  target:
    kind: Deployment
    name: grafana
- path: grafana-external-alertmanager-patch.yaml
  target:
    kind: Deployment
    name: grafana
- path: prometheus-alertmanager-patch.yaml
  target:
    kind: ConfigMap
    name: prometheus-config