apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 1m
      scrape_timeout: 1m
      evaluation_interval: 1m

    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - alertmanager.moc-monitoring.svc:9093

    rule_files:
      - /etc/prometheus/rules/*.yaml

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090"]
      
      - job_name: alertmanager
        static_configs:
          - targets: ["alertmanager.moc-monitoring.svc:9093"]
      
      - job_name: "idrac_exporter"
        scrape_interval: 3m
        scrape_timeout: 2m
        file_sd_configs:
        - files:
          - /etc/prometheus/file_sd/idrac_targets.yaml
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: idrac-exporter.moc-monitoring.svc:9348