apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moc-monitoring
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  project: default
  source:
    path: moc-monitoring/overlays/moc-infra
    repoURL: https://github.com/CCI-MOC/moc-infra-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - ApplyOutOfSyncOnly=true
