apiVersion: v1
kind: ConfigMap
metadata:
  name: librenms-config
  namespace: librenms
data:
  # Base Setup
  TZ: "America/New_York"
  PUID: "1000"
  PGID: "1000"

  # Database Config
  MYSQL_DATABASE: "librenms"
  MYSQL_USER: "librenms"
  DB_HOST: "mariadb"
  DB_TIMEOUT: "60"

  # Redis Config
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_TIMEOUT: "60"

  # RRDcached
  RRDCACHED_SERVER: "rrdcached:42217"

  # PHP / Nginx Tweaks (From librenms.env)
  MEMORY_LIMIT: "256M"
  MAX_INPUT_VARS: "1000"
  UPLOAD_MAX_SIZE: "16M"
  OPCACHE_MEM_SIZE: "128"
  REAL_IP_FROM: "0.0.0.0/32"
  REAL_IP_HEADER: "X-Forwarded-For"
  LOG_IP_VAR: "remote_addr"
  SESSION_SECURE_COOKIE: "true"

  LIBRENMS_SNMP_COMMUNITY: "librenmsdocker"
  LIBRENMS_WEATHERMAP: "false"
  LIBRENMS_WEATHERMAP_SCHEDULE: "*/5 * * * *"
  DISTRIBUTED_POLLER: "true"
