apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: librenms
labels:
- includeSelectors: true
  pairs:
    app: librenms
resources:
  - configmap.yaml
  - serviceaccount.yaml
  - mariadb
  - redis
  - web
  - dispatcher
  - rrdcached
