apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns01
spec:
  acme:
    email: ops@list.massopen.cloud
    privateKeySecretRef:
      name: letsencrypt-production-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cnameStrategy: Follow
          route53:
            region: us-east-1
            hostedZoneID: Z04486682XFINHTESP6B9
            accessKeyIDSecretRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-route53-credentials
            secretAccessKeySecretRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-route53-credentials
        selector:
          dnsZones:
            - moc-infra.massopen.cloud
