{
 "title": "BMC Status",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(idrac_exporter_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vendor",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_machine_info{instance=\"$instance\"}",
     "legendFormat": "{{manufacturer}}"
    }
   ]
  },
  {
   "title": "Global Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_health{instance=\"$instance\"}",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Memory Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(idrac_memory_module_health{instance=\"$instance\"} < 10)",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Network Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(idrac_network_interface_health{instance=\"$instance\"} < 10)",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "System Event Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(sum by (id,message,severity) (idrac_events_log_entry{instance=\"$instance\"}*1000))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_machine_info{instance=\"$instance\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_machine_info{instance=\"$instance\"}",
     "legendFormat": "{{serial}}"
    }
   ]
  },
  {
   "title": "Fan Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(idrac_sensors_fan_health{instance=\"$instance\"} < 10)",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "PSU Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(idrac_power_supply_health{instance=\"$instance\"} < 10)",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Disk Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(idrac_drive_health{instance=\"$instance\"} < 10)",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "SKU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_machine_info{instance=\"$instance\"}",
     "legendFormat": "{{sku}}"
    }
   ]
  },
  { "title": "Power and Cooling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Air Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "idrac_sensors_temperature{instance=\"$instance\",name=~\".*(Inlet|Ambient|Exhaust).*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "idrac_sensors_temperature{instance=\"$instance\",name=~\".*(CPU).*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg by (instance) (idrac_power_control_consumed_watts{instance=\"$instance\",name=~\".*Power Control|\"} > 0 or idrac_power_control_avg_consumed_watts{instance=\"$instance\",name=~\".*Power Control|\"})",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "idrac_sensors_fan_speed{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "DIMMs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (id,manufacturer,name,serial,type) (idrac_memory_module_info{instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (id,status) (idrac_memory_module_health{instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (id) (idrac_memory_module_capacity_bytes{instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (id) (idrac_memory_module_speed_mhz{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum by (id,manufacturer,mediatype,model,name,protocol,serial) (idrac_drive_info{instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (id,status) (idrac_drive_health{instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (id) (idrac_drive_capacity_bytes{instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (id) (idrac_drive_life_left_percent{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Ports",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by (id,interface_id) (idrac_network_port_link_up{instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (id,interface_id,status) (idrac_network_port_health{instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (id,interface_id) (idrac_network_port_speed_mbps{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}