apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: github
    mappingMethod: claim
    type: GitHub
    github:
      clientID: Ov23liPqrTGeZ3bJB9JX
      clientSecret:
        name: github-secret
      teams:
      - CCI-MOC/ops-core
      - CCI-MOC/moc-openshift-people
