apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notification-policies
data:
  notification_policies.yaml: |
    apiVersion: 1
    policies:
      - name: iDRAC Alerts Policy
        receiver: slack-notifications
        group_by: ['alertname', 'instance']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        routes:
          - receiver: slack-notifications
            matchers:
              - service = "idrac"