apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# No alerting resources needed here anymore

# Optionally, if this file becomes empty, you can delete it 
# and remove its reference from moc-monitoring/base/grafana/kustomization.yaml
