apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: "http://prometheus.moc-monitoring.svc:9090"
    isDefault: true
    jsonData:
      timeInterval: "60s"
