apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  server:
    host: openshift-gitops-server-openshift-gitops.apps.moc-infra.massopen.cloud
