apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['instance']
      group_wait: 1s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'slack-alert-notifications'
      routes:
      - receiver: 'slack-alert-notifications'
        matchers:
          - service = "idrac"

    receivers:
    - name: 'slack-alert-notifications'
      slack_configs:
      - api_url_file: /etc/alertmanager/secrets/slack_webhook_url
        send_resolved: true
        title: '[{{ if eq .Status "firing" }}🔥{{ else }}✅{{ end }}] {{ .CommonLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
          *Status:* {{ .Status | title }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Server:* {{ .Labels.instance }}
          *Severity:* {{ .Labels.severity | title }}
          {{ end }}