apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moc-monitoring

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

labels:
- includeSelectors: true
  pairs:
    app: alertmanager


configMapGenerator:
- name: alertmanager-config
  files:
  - config/alertmanager.yaml
  options:
    disableNameSuffixHash: true
