apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-exporter
  template:
    metadata:
      labels:
        app: snmp-exporter
    spec:
      volumes:
        - name: config-storage
          emptyDir: {}
        - name: snmp-generator-config-template
          configMap:
            name: snmp-generator-config-template
      initContainers:
        - name: insert-secret
          image: docker.io/gomplate/gomplate:v4.3.0-alpine
          volumeMounts:
            - name: config-storage
              mountPath: /config
            - name: snmp-generator-config-template
              mountPath: /config-template
          command:
            - sh
            - -c
            - |
              gomplate -f /config-template/generator_template.yml -o /config/generator.yml
          env:
            - name: IPMI_SNMP_COMMUNITY
              valueFrom:
                secretKeyRef:
                  name: ipmi-snmp-community
                  key: community
        - name: snmp-config-generator
          image: ghcr.io/ocp-on-nerc/snmp-config-generator:latest
          command:
            - sh
            - -c
            - |
              generator generate -m /mibs -g /config-output/generator.yml -o /config-output/snmp.yml
          volumeMounts:
            - name: config-storage
              mountPath: /config-output
      containers:
        - name: snmp-exporter
          image: quay.io/prometheus/snmp-exporter:latest
          args:
            - "--config.file=/config/snmp.yml"
          ports:
            - containerPort: 9116
          volumeMounts:
            - name: config-storage
              mountPath: /config
