apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moc-monitoring

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: snmp-generator-config-template
    options:
      disableNameSuffixHash: true
    files:
    - files/generator_template.yml
