apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: mount-longhorn-disk
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Mount longhorn disk
            [Mount]
            What=LABEL=longhorn
            Where=/var/mnt/longhorn
            Type=xfs
            Options=defaults
            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: "var-mnt-longhorn.mount"
