apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: librenms-secrets-es
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: librenms-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: cluster/moc-infra/librenms/librenms-secrets
        property: MYSQL_PASSWORD
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: cluster/moc-infra/librenms/librenms-secrets
        property: MYSQL_ROOT_PASSWORD
