apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  massopen.cloud/bundle: openshift-cnv
resources:
- ../../base/core/namespaces/openshift-cnv/
- ../../base/operators.coreos.com/subscriptions/kubervirt-hyperconverged/
- ../../base/operators.coreos.com/operatorgroups/kubervirt-hyperconverged-group/
