apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipmi-exporter
spec:
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            { "name": "management-vlan-215", "ips": ["10.10.0.14/22"] }
          ]
