apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rrdcached-db
  namespace: librenms
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rrdcached-journal
  namespace: librenms
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
